export const mockGuides = [
  {
    id: "g1",
    seq: "AGCTGATCGTACTGACGTA",
    start: 120,
    end: 139,
    efficiency: 0.74,
    offtargetRisk: "low",
    gcContent: 52,
  },
  {
    id: "g2",
    seq: "CGATCGTAGCTAGTCGGAT",
    start: 300,
    end: 319,
    efficiency: 0.81,
    offtargetRisk: "high",
    gcContent: 63,
  },
  {
    id: "g3",
    seq: "TTGCATGCTAGCTGATCGA",
    start: 450,
    end: 469,
    efficiency: 0.68,
    offtargetRisk: "low",
    gcContent: 47,
  },
  {
    id: "g4",
    seq: "GCTAGCTGATCGAATGCTA",
    start: 580,
    end: 599,
    efficiency: 0.89,
    offtargetRisk: "medium",
    gcContent: 53,
  },
  {
    id: "g5",
    seq: "ATCGATCGTAGCTGATCGT",
    start: 720,
    end: 739,
    efficiency: 0.76,
    offtargetRisk: "low",
    gcContent: 58,
  },
]
